name:                sdlt-service
version:             0.1.0.0
github:              "nbrick/sdlt-service"
license:             BSD3
author:              "Nic Bricknell"
maintainer:          "nebricks@gmail.com"
copyright:           "2018 Nic Bricknell"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nbrick/sdlt-service#readme>

dependencies:
- base >= 4.7 && < 5
- http-server
- url
- network

library:
  source-dirs: src

executables:
  sdlt-service-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sdlt-service

tests:
  sdlt-service-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sdlt-service
